shared:
  image: node:18
jobs:
  deploy:
    requires: [~commit]
    steps:
      - echo "hello"
  check:
    requires: [~deploy]
    steps:
      - echo "hello"
      - if [ -z "$DEPLOY" ]; then echo "環境変数が設定されていません。"; exit 1; fi
    secrets:
      - DEPLOY
  main:
    requires: [~commit]
    steps:
      - echo "hello"
  A:
    requires: [main]
    steps:
      - echo "hello"
  B:
    requires: [main]
    steps:
      - echo "hello"
  C:
    requires: [main]
    steps:
      - echo "hello"
      - if [ -z "$TEST" ]; then echo "環境変数が設定されていません。"; exit 1; fi
    secrets:
      - TEST
  D:
    requires: [main]
    steps:
      - echo "hello"
      

  upA:
    requires: [~sd@12594:downA]
    steps:
      - echo "hello"
  upB:
    requires: [~sd@12594:downB]
    steps:
      - echo "hello"
  upC:
    requires: [~sd@12594:downC]
    steps:
      - echo "hello"
  upD:
    requires: [~sd@12594:downD]
    steps:
      - echo "hello"
  TARGET:
    requires: [upA, upB, upC, upD]
    steps:
      - echo "hello"
